### ISSUE TITLE
Error: no index.html in folder

### ISSUE THREAD

**Issue by sebastianmorenoe** [MALPICAHJ1010/PALM2-BARD#2]
When I follow the instructions to deploy the frontend the following error appears:

Could not find a required file.
  Name: index.html
  Searched in: /Users/sebastianmoreno/Desktop/SANDBOX/PALM2-BARD/CHAT-FRONT/public
  
Do I miss something?

Thanks.

**Comment by MALPICAHJ1010** [comment]
Folder public, source, node_modules have been added.
